2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_setup.py:_flush():67] Configure stats pid to 1760695
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_setup.py:_flush():67] Loading settings from /home/hawk/.config/wandb/settings
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_setup.py:_flush():67] Loading settings from /home/hawk/Desktop/Heavy-Clutter-Detection/Thesis/wandb/settings
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/hawk/Desktop/Heavy-Clutter-Detection/Thesis/wandb/run-20250502_100008-4puaz0u9/logs/debug.log
2025-05-02 10:00:08,246 INFO    MainThread:1760695 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/hawk/Desktop/Heavy-Clutter-Detection/Thesis/wandb/run-20250502_100008-4puaz0u9/logs/debug-internal.log
2025-05-02 10:00:08,247 INFO    MainThread:1760695 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x70a6c5570fe0>
2025-05-02 10:00:08,247 INFO    MainThread:1760695 [wandb_init.py:init():781] calling init triggers
2025-05-02 10:00:08,247 INFO    MainThread:1760695 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'SNR': [10], 'CNR': [15], 'NU': [0.2, 0.5, 1.0], 'n_targets': 8, 'rand_n_targets': True, 'beta_end': 0.01, 'beta_start': 0.0001, 'batch_size': 16, 'num_epochs': 400, 'noise_steps': 2000, 'num_workers': 4, 'dataset_size': 500, 'time_emb_dim': 256, 'learning_rate': 0.0001, 'scheduler_type': 'cosine', '_wandb': {}}
2025-05-02 10:00:08,247 INFO    MainThread:1760695 [wandb_init.py:init():809] starting backend
2025-05-02 10:00:08,247 INFO    MainThread:1760695 [wandb_init.py:init():813] sending inform_init request
2025-05-02 10:00:08,250 INFO    MainThread:1760695 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-02 10:00:08,250 INFO    MainThread:1760695 [wandb_init.py:init():823] backend started and connected
2025-05-02 10:00:08,253 INFO    MainThread:1760695 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-05-02 10:00:08,256 INFO    MainThread:1760695 [wandb_init.py:init():915] updated telemetry
2025-05-02 10:00:08,258 INFO    MainThread:1760695 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-02 10:00:08,857 INFO    MainThread:1760695 [wandb_init.py:init():1014] starting run threads in backend
2025-05-02 10:00:08,893 INFO    MainThread:1760695 [wandb_run.py:_console_start():2454] atexit reg
2025-05-02 10:00:08,893 INFO    MainThread:1760695 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-02 10:00:08,893 INFO    MainThread:1760695 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-02 10:00:08,893 INFO    MainThread:1760695 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-02 10:00:08,894 INFO    MainThread:1760695 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-02 10:00:08,894 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:00:08,894 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:00:08,897 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:00:11,298 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:00:11,298 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:00:11,301 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:00:11,302 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:00:11,302 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:00:16,246 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:00:16,721 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:00:16,721 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:00:16,725 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:03:17,434 WARNING MsgRouterThr:1760695 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-02 10:03:17,435 INFO    MsgRouterThr:1760695 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-02 10:03:17,587 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:03:17,587 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:03:26,865 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:03:26,941 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:03:26,941 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-02 10:03:28,174 INFO    MainThread:1760695 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-02 10:03:28,194 INFO    MainThread:1760695 [wandb_run.py:_finish():2189] finishing run ari-granevich/New-Radar-diffusion/4puaz0u9
2025-05-02 10:03:28,194 ERROR   MainThread:1760695 [wandb_init.py:init():1540] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1530, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 799, in init
    wandb.run.finish()
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 483, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 425, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2182, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2190, in _finish
    with telemetry.context(run=self) as tel:
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 783, in _telemetry_callback
    self._telemetry_flush()
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 796, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-02 10:03:28,386 INFO    MainThread:1760695 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-02 10:03:28,386 INFO    MainThread:1760695 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
